---
title: "Home buying and selling"
author: "David Thompson"
date: "13/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Analysis

Given a list of concepts, with an effort and impact score, demonstrate the difference

## Step 1: Import

Import concepts

```{r load data}
concepts <- read.csv("data/concepts.csv")
```

## Step 2: Verify data

```{r look at data}
head(concepts)
```

```{r prep data}
# In the data source a higher effort score means low effort - we want to invert these so that we can see
# high effort and high impact in the top right, and low effort and low impact in the bottom left
concepts$Effort = 70 - concepts$Effort
head(concepts)
```

## Step 3: Install and load the 'ggplot2' package

```{r loading and installing ggplot2, echo=FALSE, message=FALSE}
install.packages('ggplot2')
install.packages("ggrepel")
library(ggplot2)
library(ggrepel)
```

## Step 4: Making a Scatter Plot

```{r}
ggplot(concepts, aes(x = Effort, y = Impact, label = Concept, color = Concept)) + 
  geom_point() +
  lims(x = c(10, 60), y = c(10, 60)) + 
  geom_vline(xintercept = 35) + geom_hline(yintercept = 35) + 
  geom_label_repel() +
  xlab("Effort (0 - Easier, 70 - Difficult)") +
  ylab("Impact (0 - Low, 70 - High)") +
  labs(title = "Scatterplot of HBAS Concepts: Effort and Impact", subtitle = "Concepts toward the top right are more effort, higher impact")
ggsave("concepts.png")
```
